eesast/hasura

- .travis.yml
- scripts/deploy.sh
添加CI
目标：
- 提交到master分支时，将更改运用到服务器上的hasura中
> :construction_worker: Add travis CI

- .gitignore
- README.md
在`.gitignore`中添加了macOS下系统产生的多余文件`.DS_Store`
删掉了`README.md`中的一个标点
（试一下pr）
> Modify gitignore and readme

- README.md
- config.yaml
Add cli documentation link in README.md and config.yaml
> add documatation link

- README.md
- config.yaml
- docker-compose.yaml
Changed `services - postgres - volumes` in `docker-compose.yaml`.
But I'm not sure about the change.
> change docker storage place

- metadata/tables.yaml
- migrations/1615567334937_thuai_room_thuai_team/down.sql
- migrations/1615567334937_thuai_room_thuai_team/up.sql
- package.json
- yarn.lock
增加thuai_room,thuai_manager表，以及room_team关系表
> add thuai_room

- .env
- metadata/tables.yaml
- migrations/1611339525841_create_table_public_thuai/down.sql
- migrations/1611339525841_create_table_public_thuai/up.sql
- migrations/1611339585651_create_table_public_thuai_user/down.sql
- migrations/1611339585651_create_table_public_thuai_user/up.sql
- migrations/1611339677159_alter_table_public_thuai_add_column_team_leader/down.sql
- migrations/1611339677159_alter_table_public_thuai_add_column_team_leader/up.sql
- migrations/1611339704525_set_fk_public_thuai_team_leader/down.sql
- migrations/1611339704525_set_fk_public_thuai_team_leader/up.sql
- migrations/1613353000499_alter_table_public_thuai_add_column_team_member1/down.sql
- migrations/1613353000499_alter_table_public_thuai_add_column_team_member1/up.sql
- migrations/1613353020807_alter_table_public_thuai_add_column_team_member2/down.sql
- migrations/1613353020807_alter_table_public_thuai_add_column_team_member2/up.sql
- migrations/1613353285334_alter_table_public_thuai_alter_column_team_leader/down.sql
- migrations/1613353285334_alter_table_public_thuai_alter_column_team_leader/up.sql
- migrations/1613379071821_alter_table_public_thuai_add_column_created_at/down.sql
- migrations/1613379071821_alter_table_public_thuai_add_column_created_at/up.sql
- migrations/1613379217329_alter_table_public_thuai_alter_column_team_leader/down.sql
- migrations/1613379217329_alter_table_public_thuai_alter_column_team_leader/up.sql
- migrations/1613379279396_alter_table_public_thuai_add_column_invited_code/down.sql
- migrations/1613379279396_alter_table_public_thuai_add_column_invited_code/up.sql
- migrations/1613379395825_set_fk_public_thuai_team_leader/down.sql
- migrations/1613379395825_set_fk_public_thuai_team_leader/up.sql
- migrations/1613383492884_alter_table_public_thuai_drop_column_team_member1/down.sql
- migrations/1613383492884_alter_table_public_thuai_drop_column_team_member1/up.sql
- migrations/1613383513033_alter_table_public_thuai_drop_column_team_member2/down.sql
- migrations/1613383513033_alter_table_public_thuai_drop_column_team_member2/up.sql
- migrations/1613465510981_alter_table_public_thuai_alter_column_team_leader/down.sql
- migrations/1613465510981_alter_table_public_thuai_alter_column_team_leader/up.sql
add root and eesenior permission on thuai
> Thuai permission

- migrations/1619011854036_alter_table_public_thuai_room_add_column_created_at/down.sql
- migrations/1619011854036_alter_table_public_thuai_room_add_column_created_at/up.sql
- migrations/1619012295293_alter_table_public_thuai_room_add_column_show_id/down.sql
- migrations/1619012295293_alter_table_public_thuai_room_add_column_show_id/up.sql
add creat_at, show_id in thuai room list
>  add creat_at, show_id

- metadata/tables.yaml
- migrations/1629002263025_squashed/down.sql
- migrations/1629002263025_squashed/up.sql
All tables with thuai are deprecated, currently not deleted for referrence.
> refactor: add team_user, modify team

- metadata/tables.yaml
- migrations/1645919192364_alter_table_public_contest_add_column_contest_type/down.sql
- migrations/1645919192364_alter_table_public_contest_add_column_contest_type/up.sql
- migrations/1645919269224_alter_table_public_contest_alter_column_contest_type/down.sql
- migrations/1645919269224_alter_table_public_contest_alter_column_contest_type/up.sql
- package.json
- yarn.lock
Modify the permissions of contest, contest_manager.Add contest_type in contest.
> Modify some permissions

- metadata/tables.yaml
学生可以查找contest_team中对应的contest_id
辅导员也可以加入和退出队伍
> update student and counselor select permission

- metadata/tables.yaml
- migrations/1647096381176_set_fk_public_thuai_room_team_thuai_team_id/down.sql
- migrations/1647096381176_set_fk_public_thuai_room_team_thuai_team_id/up.sql
增加了thuai_room_team team_id 与 thuai 中 team_id 的外键和联系
> feat: :art: add thuai_room_team foreign key & relationship

- metadata/tables.yaml
- migrations/1647695807287_alter_table_public_contest_room_add_column_contest_id/down.sql
- migrations/1647695807287_alter_table_public_contest_room_add_column_contest_id/up.sql
- migrations/1647695868001_set_fk_public_contest_room_contest_id/down.sql
- migrations/1647695868001_set_fk_public_contest_room_contest_id/up.sql
- migrations/1647696147072_set_fk_public_contest_room_team_team_id/down.sql
- migrations/1647696147072_set_fk_public_contest_room_team_team_id/up.sql
- migrations/1647697050125_alter_table_public_contest_room_drop_column_contest_name/down.sql
- migrations/1647697050125_alter_table_public_contest_room_drop_column_contest_name/up.sql
1.  contest_room删除了contest_name属性，改为contest_id并设置为外键 
3. contest_room_team设置了team_id为外键并增加了相应联系
> perf: :zap: 对contest_room和contest_room_team表进行了必要的修改

- metadata/tables.yaml
- migrations/1648224906376_alter_table_public_contest_team_add_column_submitted_code_num/down.sql
- migrations/1648224906376_alter_table_public_contest_team_add_column_submitted_code_num/up.sql
Record the number of the submitted code.
> Add Submitted_code_num for Contest_team

- metadata/tables.yaml
Allow student insert, update, delete contest_info.
> Add permissions for student

- metadata/tables.yaml
- migrations/1700418770835_create_table_public_users/down.sql
- migrations/1700418770835_create_table_public_users/up.sql
- migrations/1700418820365_alter_table_public_users_alter_column_uuid/down.sql
- migrations/1700418820365_alter_table_public_users_alter_column_uuid/up.sql
- migrations/1700418961637_modify_primarykey_public_users/down.sql
- migrations/1700418961637_modify_primarykey_public_users/up.sql
- migrations/1700418970750_alter_table_public_users_alter_column_student_no/down.sql
- migrations/1700418970750_alter_table_public_users_alter_column_student_no/up.sql
> feat(users): add a new table users

- migrations/1708850924494_set_fk_public_contest_team_team_leader_uuid/down.sql
- migrations/1708850924494_set_fk_public_contest_team_team_leader_uuid/up.sql
- migrations/1708850949259_set_fk_public_aid_application_student_uuid/down.sql
- migrations/1708850949259_set_fk_public_aid_application_student_uuid/up.sql
- migrations/1708850981893_set_fk_public_contest_manager_user_uuid/down.sql
- migrations/1708850981893_set_fk_public_contest_manager_user_uuid/up.sql
- migrations/1708851010936_set_fk_public_contest_team_member_user_uuid/down.sql
- migrations/1708851010936_set_fk_public_contest_team_member_user_uuid/up.sql
- migrations/1708851017720_set_fk_public_honor_application_student_uuid/down.sql
- migrations/1708851017720_set_fk_public_honor_application_student_uuid/up.sql
- migrations/1708851034569_set_fk_public_mentor_application_mentor_uuid/down.sql
- migrations/1708851034569_set_fk_public_mentor_application_mentor_uuid/up.sql
- migrations/1708851044990_set_fk_public_mentor_application_student_uuid/down.sql
- migrations/1708851044990_set_fk_public_mentor_application_student_uuid/up.sql
- migrations/1708851058094_set_fk_public_mentor_available_mentor_uuid/down.sql
- migrations/1708851058094_set_fk_public_mentor_available_mentor_uuid/up.sql
- migrations/1708851079099_set_fk_public_mentor_info_mentor_uuid/down.sql
- migrations/1708851079099_set_fk_public_mentor_info_mentor_uuid/up.sql
- migrations/1708851086379_set_fk_public_mentor_message_from_uuid/down.sql
- migrations/1708851086379_set_fk_public_mentor_message_from_uuid/up.sql
- migrations/1708851099672_set_fk_public_mentor_message_to_uuid/down.sql
- migrations/1708851099672_set_fk_public_mentor_message_to_uuid/up.sql
- migrations/1708851376397_set_fk_public_scholarship_application_student_uuid/down.sql
- migrations/1708851376397_set_fk_public_scholarship_application_student_uuid/up.sql
将外键约束由restrict改为cascade，这样uuid改变时诸如team_leader_uuid会随之改变。
> fix(uuid): foreign key cascade

- metadata/tables.yaml
- migrations/1709484224781_alter_table_public_mentor_message_alter_column_from_id/down.sql
- migrations/1709484224781_alter_table_public_mentor_message_alter_column_from_id/up.sql
- migrations/1709484231334_alter_table_public_mentor_message_alter_column_to_id/down.sql
- migrations/1709484231334_alter_table_public_mentor_message_alter_column_to_id/up.sql
- migrations/1709484444605_alter_table_public_mentor_application_alter_column_mentor_id/down.sql
- migrations/1709484444605_alter_table_public_mentor_application_alter_column_mentor_id/up.sql
- migrations/1709484449866_alter_table_public_mentor_application_alter_column_student_id/down.sql
- migrations/1709484449866_alter_table_public_mentor_application_alter_column_student_id/up.sql
- migrations/1709485179476_modify_primarykey_public_mentor_info/down.sql
- migrations/1709485179476_modify_primarykey_public_mentor_info/up.sql
- migrations/1709485190641_alter_table_public_mentor_info_alter_column_mentor_id/down.sql
- migrations/1709485190641_alter_table_public_mentor_info_alter_column_mentor_id/up.sql
mentor_message: from_id & to_id nullable
mentor_info: primary key to mentor_uuid. mentor_id nullable
> refact(mentor): mentor info, message. id->uuid

- metadata/actions.graphql
- metadata/actions.yaml
- metadata/tables.yaml
- migrations/1709523437265_alter_table_public_mentor_available_add_unique_mentor_uuid/down.sql
- migrations/1709523437265_alter_table_public_mentor_available_add_unique_mentor_uuid/up.sql
- migrations/1709523498385_modify_primarykey_public_mentor_available/down.sql
- migrations/1709523498385_modify_primarykey_public_mentor_available/up.sql
- migrations/1709523516498_alter_table_public_mentor_available_alter_column_mentor_id/down.sql
- migrations/1709523516498_alter_table_public_mentor_available_alter_column_mentor_id/up.sql
Crucial for mentor application.
> Modify hasura permissions, from id -> uuid

- package.json
- yarn.lock
> Revert "fix(deps): update dependency hasura-cli to v2.38.0"

- migrations/1750137516085_alter_table_public_contest_add_column_max_teammember_limit/down.sql
- migrations/1750137516085_alter_table_public_contest_add_column_max_teammember_limit/up.sql
> Revert "added contest team member limit"
